server:
  port: 8080

spring:
  data:
    rest:
      base-path: /api
  datasource:
    url: jdbc:mysql://localhost:3306/react
    username: root
    password: jazur899124
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop